import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
//import "./../globals.css";
import Image from "next/image";
import coding from "./../../assets/coding.png";

import Menu from "../../components/menu";
import Sidebar from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthenticationLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Menu />
      <div className="grid grid-cols-15">
        <Sidebar />
        <div className="col-span-14 pl-4 pt-4  bg-emerald-100">{children}</div>
      </div>
    </>
  );
}
